import React from 'react'

import styled from 'styled-components'

import { FlexColumn, TextWrapper } from 'styles/components'
import { themeColor } from 'styles/theme'

const ModalWrapper = styled(FlexColumn)`
  border-top: 8px solid ${themeColor.text3};
  margin-top: 12px;
  padding: 6%;
  align-items: flex-start;
  background-color: ${themeColor.background1};
`
const ManifestoModal: React.FC = () => {
  return (
    <ModalWrapper>
      <TextWrapper fontSize={'xxl'} fontWeight={'bold'} fontFamily={'title'} lineHeight={49}>
        {'Project Manifesto'}
      </TextWrapper>
      <TextWrapper fontFamily={'title'} lineHeight={32} margin={'12px 0'}>
        {
          'The art engine for this project is driven by math equations. It does not claim to be driven by AI. The art is generated by old fashioned Human Intelligence. You are the Creator. There is no guide or instructional videos for creating the pieces. Enjoy. Full commercial rights are granted to the holder of a Blockchain Hypotrochoids for any personal and/or commercial use.'
        }
      </TextWrapper>
      <TextWrapper fontFamily={'title'} lineHeight={32} margin={'12px 0'}>
        {
          'The art engine for this project is driven by math equations. It does not claim to be driven by AI. The art is generated by old fashioned Human Intelligence. You are the Creator. There is no guide or instructional videos for creating the pieces. Enjoy. Full commercial rights are granted to the holder of a Blockchain Hypotrochoids for any personal and/or commercial use.'
        }
      </TextWrapper>
      <TextWrapper fontFamily={'title'} lineHeight={32} margin={'12px 0'}>
        {
          'The art engine for this project is driven by math equations. It does not claim to be driven by AI. The art is generated by old fashioned Human Intelligence. You are the Creator. There is no guide or instructional videos for creating the pieces. Enjoy. Full commercial rights are granted to the holder of a Blockchain Hypotrochoids for any personal and/or commercial use.'
        }
      </TextWrapper>
    </ModalWrapper>
  )
}

export default ManifestoModal
